# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  UI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          package_json_file: ui/package.json
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ui
        run: pnpm install
      - name: Lint
        working-directory: ui
        run: pnpm lint
      - name: Test
        working-directory: ui
        run: pnpm test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: ui
          parallel: true
      - name: Build UI
        working-directory: ui
        run: pnpm build

  Python:
    name: Python ${{ matrix.python }}, OctoPrint ${{ matrix.octoprint }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        octoprint: [ "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "2.0" ]
        exclude:
          # These versions are not compatible to each other:
          - octoprint: 1.5
            python: 3.10
          - octoprint: 1.5
            python: 3.11
          - octoprint: 1.5
            python: 3.12
          - octoprint: 1.5
            python: 3.13
          - octoprint: 1.6
            python: 3.10
          - octoprint: 1.6
            python: 3.11
          - octoprint: 1.6
            python: 3.12
          - octoprint: 1.6
            python: 3.13
          - octoprint: 1.7
            python: 3.10
          - octoprint: 1.7
            python: 3.11
          - octoprint: 1.7
            python: 3.12
          - octoprint: 1.7
            python: 3.13
          - octoprint: 1.8
            python: 3.10
          - octoprint: 1.8
            python: 3.11
          - octoprint: 1.8
            python: 3.12
          - octoprint: 1.8
            python: 3.13
          - octoprint: 1.9
            python: 3.12
          - octoprint: 1.9
            python: 3.13
          - octoprint: 1.10
            python: 3.13
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Get pip cache dir
        id: pipCache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache pip modules
        uses: actions/cache@v5
        with:
          path: ${{ steps.pipCache.outputs.dir }}
          key: ${{ runner.os }}-build-cache-pip-python-${{ matrix.python }}-octoprint-${{ matrix.octoprint}}
      - name: Install setuptools 81
        # https://github.com/pypa/setuptools/issues/3085
        run: pip install 'setuptools>=81.0.0,<82.0.0'
      - name: Install OctoPrint
        # see https://stackoverflow.com/questions/49854628/how-do-i-pip-install-the-latest-patch-number-of-a-package
        run: |
          if [ "${{ matrix.octoprint }}" = "2.0" ]; then
            pip install octoprint==2.0.0rc1
          else
            pip install octoprint~=${{ matrix.octoprint }}.0
          fi
      - name: Install Wheel
        # see https://community.octoprint.org/t/setuptools-error-while-installing-plugin-octoklipper-on-manual-op-installation/51387
        run: pip install wheel
      - name: Make liblgpio.so
        if: ${{ matrix.python == '3.13' }}
        # see https://github.com/borisbu/OctoRelay/issues/346#issuecomment-2849009685
        run: |
          wget https://abyz.me.uk/lg/lg.zip
          unzip lg.zip
          cd lg
          make
          sudo make install
      - name: Install OctoRelay
        run: pip install -e .
      - name: Prepare testing environment
        run: pip install coverage pylint mypy
      - name: Test
        working-directory: tests
        run: python -m coverage run -m unittest test*.py
      - name: Report the coverage
        working-directory: tests
        run: |
          python -m coverage lcov --omit=test*
          python -m coverage report --show-missing --omit=test*
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: python-${{ matrix.python }}-octoprint-${{ matrix.octoprint }}
          parallel: true
          file: ./tests/coverage.lcov
      - name: Types checking
        run: mypy ./octoprint_octorelay
      - name: Lint
        run: pylint --rcfile=.pylintrc ./octoprint_octorelay ./tests/*.py

  finish:
    needs: [UI, Python]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        continue-on-error: true
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
